version: '3.1'

services:

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: donkey_mobile_db

  mongo:
    container_name: mongodb
    image: mongo:6.0.5
    ports:
      - '27017:27017'
    env_file:
      - .env
    volumes:
      - mongo:/data/db
    networks:
      - "donkey_network"

  mongo-seed:
    env_file:
      - .env
    build:
      context: ./mongo-seed
      dockerfile: Dockerfile
      args:
        - DATABASE_URI=$DATABASE_URI
        - USERNAME=$MONGO_INITDB_ROOT_USERNAME
        - PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    depends_on:
      - mongo
    networks:
      - "donkey_network"

volumes:
  mongo:

networks:
  donkey_network: