# Use this extension https://marketplace.visualstudio.com/items?itemName=anweber.vscode-httpyac
@host=http://localhost:3000/api

###
# @name user
POST /users
Content-Type: application/json

{
    "firstName": "Tim",
    "lastName": "Test",
    "email": "test@example.com"
}

###
# @ref user
DELETE /users
Authorization: Bearer {{user._id}}

###
# @name post
# @ref user
POST /posts
Authorization: Bearer {{user._id}}
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="description"

Lorem ipsum 
--WebKitFormBoundary
Content-Disposition: form-data; name="document"; filename="document.pdf"
Content-Type: application/pdf

< ./test-data/document.pdf
--WebKitFormBoundary
Content-Disposition: form-data; name="images"; filename="image2.webp"
Content-Type: image/webp

< ./test-data/image2.webp
--WebKitFormBoundary
Content-Disposition: form-data; name="images"; filename="image1.png"
Content-Type: image/png

< ./test-data/image1.png
--WebKitFormBoundary--

###
GET /posts

###
# @ref post
GET /posts/{{post._id}}

###
# @name comment
# @ref user
# @ref post
POST /posts/{{post._id}}/comments
Authorization: Bearer {{user._id}}
Content-Type: application/json

{
    "comment": "Lorem ipsum"
}

###
# @ref post
GET /posts/{{post._id}}/comments

###
# @ref user
# @ref post
# @ref comment
DELETE /posts/{{post._id}}/comments/{{comment._id}}
Authorization: Bearer {{user._id}}

###
# @ref user
# @ref post
DELETE /posts/{{post._id}}
Authorization: Bearer {{user._id}}